env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - binary: barreldb
    id: barreldb
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "main.buildVersion={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"
    dir: ./cmd/server/

  - skip: true
    id: barrel_lib

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE
      - cmd/server/config.sample.toml
